[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_dvpn = "2yMtc57KbBGtMEyubqc75Dr21s5UdgmwYnYRTLosfv9t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sadeq/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
