[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dvpn_program = "DPVrfneJ2xeneEmXNMDSHWFoA7gzkc6D97MSdxqte8hE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "new-app.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
dvpn_program = "DPVrfneJ2xeneEmXNMDSHWFoA7gzkc6D97MSdxqte8hE"


